<a href="https://colab.research.google.com/github/june0348/Test/blob/master/3%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_%EA%B9%80%EC%A4%80%EB%AF%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3주차 과제
- 학습률 최적화
- 군집 분석(병합 계층 군집) 구현 클론 코딩
- Cost function 구현

## 1. 학습률 최적화

간단한 예제를 통해 학습률 최적화의 중요성에 대해서 확인 해 보도록 하겠습니다.

아래 링크에서 __1단계만__에 손실 곡선의 최저점에 도달하게 하는 학습률을 찾아 정답을 적어주세요

링크: https://developers.google.com/machine-learning/crash-course/fitter/graph?hl=ko

### 정답 : 1.6

## 2. 군집 분석(병합 계층 군집) 구현 클론 코딩

군집 분석 강의(군집문제[2] 3:10 ~ 5:20 부분)를 보고 코드를 따라 치며 출력 결과(과제 설명 페이지 참고)를 만드세요. 

강의에서는 데이터 시각화까지 진행하지만 
과제에서는 표를 출력하는 것 까지만 하시면 됩니다.

3주차 과제 안내 페이지를 보시면 표에 대한 이미지가 있습니다. 참고해주세요

In [17]:
# 굽집 분석을 진행하기 위한 샘플 생성
import numpy as np                                                              # 넘파이을 사용하여 구축
np.random.seed(123)
X = np.random.random_sample([5, 3]) * 10                                        # 무작위 함수를 통해 [5,3]행렬에 0~1사이의 임의의 실수 생성 및 거리값을 위한 10정도 곱

X

array([[6.96469186, 2.86139335, 2.26851454],
       [5.51314769, 7.1946897 , 4.2310646 ],
       [9.80764198, 6.84829739, 4.80931901],
       [3.92117518, 3.43178016, 7.29049707],
       [4.38572245, 0.59677897, 3.98044255]])

In [18]:
import pandas as pd                                                 
variables = ['X', 'Y', 'Z']
labels = ['ID_0', 'ID_1', 'ID_2', 'ID_3', 'ID_4']
df = pd.DataFrame(X, columns=variables, index=labels)                           # 판다스에 데이터 프레임 방식으로 저장
df

X         Y         Z
ID_0  6.964692  2.861393  2.268515
ID_1  5.513148  7.194690  4.231065
ID_2  9.807642  6.848297  4.809319
ID_3  3.921175  3.431780  7.290497
ID_4  4.385722  0.596779  3.980443

In [19]:
# 계층군집 알고리즘의 입력에 사용할 거리 행렬 계산
# scipy.spatial.distace 모듈에서 pdist 함수를 사용
from scipy.spatial.distance import pdist, squareform                            # pdist() 축약된 거리 행렬

Y = pdist(df)        # df < - X, Y, Z
Y

# 입력으로 들어온 X,Y,Z 값에 대하여 축약된 거리 행렬 값으로 반환

array([4.973534  , 5.51665266, 5.89988504, 3.83539555, 4.34707339,
       5.10431109, 6.69823298, 7.24426159, 8.31659367, 4.382864  ])

In [20]:
row_dist = pd.DataFrame(squareform(pdist(df, metric='euclidean')),              # 거리 계산은 유클리디안('enclidean') / squareform(): 거리행렬 벡터를 행렬형식으로 변환
                        columns = labels, index=labels)

# 완전연결 병합방식을 적용하기 위해 scipy.cluster.hierarchy 모듈에 linkage 함수를 사용
from scipy.cluster.hierarchy import linkage

# linkage 함수에 무작정 squareform을 통과한 데이터 프레임 넣어주면 기대한 값과는 다른 결과가 나옴
row_clusters = linkage(row_dist, 
                       method='complete', 
                       metric='euclidean')

# help(linkage)
# pdist 함수에서 축약된 거리 행렬을 입력 속성으로 사용.
# linkage 함수에서 초기 데이터 배열을 전달하고 'euclidean' 지표를 매개변수로 사용.

row_clusters

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  # Remove the CWD from sys.path while we load stuff.


array([[ 0.        ,  4.        ,  6.52197264,  2.        ],
       [ 1.        ,  2.        ,  6.72960262,  2.        ],
       [ 3.        ,  5.        ,  8.53924727,  3.        ],
       [ 6.        ,  7.        , 12.44482356,  5.        ]])

In [21]:
# 축약된 거리 행렬을 사용하여 올바른 거리 행렬 얻음
row_clusters = linkage(pdist(df, metric='euclidean'), 
                       method='complete')

row_clusters

array([[0.        , 4.        , 3.83539555, 2.        ],
       [1.        , 2.        , 4.34707339, 2.        ],
       [3.        , 5.        , 5.89988504, 3.        ],
       [6.        , 7.        , 8.31659367, 5.        ]])

In [22]:
# 원본 샘플 행렬을 사용하여 올바른 연결 행렬을 얻음
row_clusters = linkage(df.values, 
                       method='complete', 
                       metric='euclidean')
row_clusters

array([[0.        , 4.        , 3.83539555, 2.        ],
       [1.        , 2.        , 4.34707339, 2.        ],
       [3.        , 5.        , 5.89988504, 3.        ],
       [6.        , 7.        , 8.31659367, 5.        ]])

In [23]:
# 군집 결과를 자세히 살펴보기 위해 군집결과를 판다스 데이터프레임(pd.DataFrame) 형식으로 변환
pd.DataFrame(row_clusters,
             columns = ['row label 1', 'row label 2', 'distance', 'no. of items in clust.'], 
             index = ['cluster %d' %(i+1) for i in range(row_clusters.shape[0])])

row label 1  row label 2  distance  no. of items in clust.
cluster 1          0.0          4.0  3.835396                     2.0
cluster 2          1.0          2.0  4.347073                     2.0
cluster 3          3.0          5.0  5.899885                     3.0
cluster 4          6.0          7.0  8.316594                     5.0

## 3. Cost function 구현
## $$cost(W) =  \frac{1}{n}\sum_{i=1}^n (Wx^{(i)}-y^{(i)})^2$$

### 데이터(X, Y)

In [0]:
# 제공된 데이터는 변경 할 수 없습니다.
x = [1, 2, 3]
y = [2, 4, 6]

### cost function을 파이썬으로 구현하세요.
pass를 지우고 cost_func 함수를 완성하세요.

가중치(Weight)를 입력하면 코스트(cost)를 계산하는 함수를 만드는게 목적입니다.

In [0]:
# W(가중치) 데이터 타입 -> int or float
# x(학습 데이터) 데이터 타입 -> list
# y(정답 데이터) 데이터 타입 -> list
# cost_func 함수 리턴값 타입 -> float
# cost_func 함수 리턴값 = cost 값
# W:가중치, x:학습 데이터 y:정답 데이터

def cost_func(W, x, y):
  n = len(x)
  result = 0
  for i in range(0, n):
    A = ((W*x[i]-y[i])**2)/n
    result += A
  return result

예시) x가 [1, 2] 이고 y가 [3, 6] 그리고 W가 4 일 경우  cost_func(W, x, y)함수의 리턴값은 2.5

### cost_func을 활용하여 웨이트(Weight)가 -5부터 5까지의 변화에 따른 코스트(cost)를 출력 해주세요.

In [26]:
# 여기 코드셀은 변경하지 마세요.
# 완성된 함수를 확인하는 과정으로 해당 코드셀을 실행해서 정상 출력되면 정답!
# 주의! 에러가 날 경우 데이터 코드셀과 cost function 코드셀을 실행했는지 확인해주세요.
for feed_W in range(-5, 6, 1):
  curr_cost = cost_func(feed_W, x, y)
  print("{:6.3f} | {:10.5f}".format(feed_W, curr_cost))

-5.000 |  228.66667
-4.000 |  168.00000
-3.000 |  116.66667
-2.000 |   74.66667
-1.000 |   42.00000
 0.000 |   18.66667
 1.000 |    4.66667
 2.000 |    0.00000
 3.000 |    4.66667
 4.000 |   18.66667
 5.000 |   42.00000
